### PR TITLE
Fix custom validator not ending with _validator

### LINKED ISSUE #2336: Issue with CustomValidator if it's name doesn't end with "_validator"
I found a issue while registering a custom validator in our app. The [delete_suffix!](https://github.com/ruby-grape/grape/blob/d1dfdccca242e00d4d88064a013f92e89a76dbd2/lib/grape/validations/validators/base.rb#L67)! will return `nil` if no change was made.  We need to remove the `!`.

I'll open a PR to fix it

### PR DESCRIPTION
**Pull request by ericproulx**
Fix #2336

### CODE REVIEW

File: spec/grape/validations/validators/base_spec.rb [hunk 1]
```diff
@@ -0,0 +1,28 @@
+# frozen_string_literal: true
+
+RSpec.describe Grape::Validations::Validators::Base do
+  describe '#inherited' do
+    # I tried with `Class.new(Grape::Validations::Validators::Base) but `inherited` is not called.
```
Comment (dblock) [inline spec/grape/validations/validators/base_spec.rb:5]: Does https://avdi.codes/classnew-and-inherited/ help?

File: CHANGELOG.md [hunk 2]
```diff
@@ -13,6 +13,7 @@
 #### Fixes
 
 * [#2328](https://github.com/ruby-grape/grape/pull/2328): Don't cache Class.instance_methods - [@byroot](https://github.com/byroot).
+* [#2337](https://github.com/ruby-grape/grape/pull/2337): Fix custom validator registering - [@ericproulx](https://github.com/ericproulx).
```
Comment (dblock) [inline CHANGELOG.md:16]: Let's say "Fix: allow custom validators that do not end with `_validator`"?

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
> 1 Warning
> ⚠️	There're library changes, but not tests. That's OK as long as you're refactoring existing code.
> Generated by 🚫 [Danger](https://danger.systems/)

Hmmmm... this clearly isn't right.

**Comment by dblock** [comment]
Thanks for fixing this.
