### PR TITLE
coercing of nested arrays

### LINKED ISSUE #2041: Array[Array[X]] Error
While upgrading from version 1.2.5 to 1.3.2 I figure out that the coerce of type Array[Array[String]]  or Array[Array[Integer]] turns into the following error : 

```
Failure/Error: MAPPING.fetch(type) { scope.const_get(type.name) }

     NoMethodError:
       undefined method `name' for [String]:Array
     # ./lib/grape/validations/types/primitive_coercer.rb:33:in `block in initialize'
     # ./lib/grape/validations/types/primitive_coercer.rb:33:in `fetch'
     # ./lib/grape/validations/types/primitive_coercer.rb:33:in `initialize'
     # ./lib/grape/validations/types/array_coercer.rb:21:in `new'
     # ./lib/grape/validations/types/array_coercer.rb:21:in `initialize'
     # ./lib/grape/validations/types/build_coercer.rb:64:in `new'
     # ./lib/grape/validations/types/build_coercer.rb:64:in `create_coercer_instance'
     # ./lib/grape/validations/types/build_coercer.rb:40:in `block in build_coercer'
     # ./lib/grape/validations/types/build_coercer.rb:77:in `cache_instance'
     # ./lib/grape/validations/types/build_coercer.rb:39:in `build_coercer'
     # ./lib/grape/validations/validators/coerce.rb:26:in `initialize'
     # ./lib/grape/validations/validator_factory.rb:7:in `new'
     # ./lib/grape/validations/validator_factory.rb:7:in `create_validator'
     # ./lib/grape/endpoint.rb:362:in `block in run_validators'
     # ./lib/grape/endpoint.rb:362:in `map'
     # ./lib/grape/endpoint.rb:362:in `run_validators'
     # ./lib/grape/endpoint.rb:262:in `block in run'
     # ./lib/grape/endpoint.rb:245:in `run'
     # ./lib/grape/endpoint.rb:320:in `block in build_stack'
     # ./lib/grape/middleware/base.rb:35:in `call!'
     # ./lib/grape/middleware/base.rb:28:in `call'
     # ./lib/grape/middleware/error.rb:39:in `block in call!'
     # ./lib/grape/middleware/error.rb:38:in `catch'
     # ./lib/grape/middleware/error.rb:38:in `call!'
     # ./lib/grape/middleware/base.rb:28:in `call'
     # ./lib/grape/endpoint.rb:229:in `call!'
     # ./lib/grape/endpoint.rb:223:in `call'
     # ./lib/grape/router/route.rb:76:in `exec'
     # ./lib/grape/router.rb:136:in `process_route'
     # ./lib/grape/router.rb:89:in `block in identity'
     # ./lib/grape/router.rb:108:in `transaction'
     # ./lib/grape/router.rb:87:in `identity'
     # ./lib/grape/router.rb:72:in `block in call'
     # ./lib/grape/router.rb:152:in `with_optimization'
     # ./lib/grape/router.rb:71:in `call'
     # ./lib/grape/api/instance.rb:167:in `call'
     # ./lib/grape/api/instance.rb:71:in `call!'
     # ./lib/grape/api/instance.rb:66:in `call'
     # ./lib/grape/api.rb:68:in `call'
     # ./spec/support/array_array.rb:7:in `block (3 levels) in <top (required)>'
     # ./spec/support/array_array.rb:35:in `block (4 levels) in <top (required)>'
```

Here is a spec to reproduce the above error. The issue appears into version 1.3.0.
```
# frozen_string_literal: true

require 'spec_helper'

describe Grape::Validations::DefaultValidator do
  describe '#validate!' do
    subject(:validate) { post path, params }

    module ValidationsSpec
      module DefaultValidatorSpec
        class API < Grape::API
          rescue_from Grape::Exceptions::ValidationErrors do |e|
            error!(e.errors.transform_keys! { |key| key.join(',') }, 400)
          end

          params do
            requires :skills, type: Array[Array[String]]
            optional :matrix, type: Array[Array[Integer]]
          end

          post '/array-array-type' do
          end
        end
      end
    end

    def app
      ValidationsSpec::DefaultValidatorSpec::API
    end

    context 'array of array of string should be correctly coerced.' do
      let(:path) { '/array-array-type' }
      let(:params) do
        {
          skills: [%w[a b]],
          matrix: [[0, 1], [1, 0]]
        }
      end

      it 'It should return array of array of string' do
        validate
        expect(JSON.parse(last_response.body)).to eq(
          'skills' => [%w[a b]],
          'matrix' => [[0, 1], [1, 0]]
        )
      end
    end
  end
end
```

### PR DESCRIPTION
**Pull request by dnesteryuk**
It is a regression which was introduced after migrating to DryTypes. Now, it is again possible to define an array of arrays as a type.

```ruby
params do
  requires :skills, type: Array[[String]]
end
```

Fixes #2041

### CODE REVIEW

File: lib/grape/validations/types/array_coercer.rb [hunk 1]
```diff
@@ -18,26 +18,27 @@ def initialize(type, strict = false)
           super
 
           @coercer = scope::Array
-          @elem_coercer = PrimitiveCoercer.new(type.first, strict)
+          @nested = type.first.is_a?(Array)
```
Comment (dblock) [inline lib/grape/validations/types/array_coercer.rb:21]: Array or any kind of enumerable? Sets of sets?

File: lib/grape/validations/types/dry_type_coercer.rb [hunk 2]
```diff
@@ -17,8 +17,37 @@ module Types
       # but check its type. More information there
       # https://dry-rb.org/gems/dry-types/1.2/built-in-types/
       class DryTypeCoercer
+        class << self
+          def inherited(klass)
+            # share the hash with classes, so inheritors could will it
+            klass.instance_variable_set(:@collection_coercers, collection_coercers)
```
Comment (dblock) [inline lib/grape/validations/types/dry_type_coercer.rb:23]: Feels dirty. Maybe we can add a `coercers=` method?

File: spec/grape/validations/types/array_coercer_spec.rb [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+    end
+
+    context 'an array of sets' do
+      let(:type) { Array[Set[Integer]] }
+
+      it 'coerces elements in the nested set' do
+        expect(subject.call([%w[10 20]])).to eq([Set[10, 20]])
+        expect(subject.call([['10'], ['20']])).to eq([Set[10], Set[20]])
+      end
+    end
```
Comment (dblock) [inline spec/grape/validations/types/array_coercer_spec.rb:33]: Let's add a test with one more level of nesting?

Can I do a set of arrays?

**Comment by dnesteryuk** [comment]
@dblock thanks for the quick review :+1: I've improved the design :blush: We can avoid sharing any structure with inheritors.

**Comment by dblock** [comment]
> @dblock thanks for the quick review 👍 I've improved the design 😊 We can avoid sharing any structure with inheritors.

Better.
