### PR TITLE
Params: Fix coerce_with helper and Arrays types

### LINKED ISSUE #1324: Can't use coerce_with and Array[Integer] or Array[String] param types
Hello,

we're having trouble using ```coerce_with``` helper since this commit: https://github.com/ruby-grape/grape/commit/7411e2f8e0cc38fc6db703f53da06c6d010601a1

Here is a test showing the problem we have:
https://github.com/ngonzalez/grape-test-app/blob/master/test/controllers/api_test.rb
https://github.com/ngonzalez/grape-test-app/blob/master/app/api/twitter/api.rb

```
# Running:

F...

Finished in 0.188642s, 21.2042 runs/s, 37.1073 assertions/s.

  1) Failure:
ApiTest#test_test_2 [/home/ngonzalez/Sites/grape-test-app/test/controllers/api_test.rb:18]:
Expected: [1, 2, 3, 4]
  Actual: {"error"=>"values is invalid"}

4 runs, 7 assertions, 1 failures, 0 errors, 0 skips
```

```Array``` type is working fine with ```coerce_with``` but we need ```Array[Integer]```

We have a branch with the same test and Grape version freezed:
https://github.com/ngonzalez/grape-test-app/compare/before-changes

In this branch, tests pass without errors:
```
# Running:

....

Finished in 0.197692s, 20.2335 runs/s, 40.4669 assertions/s.

4 runs, 8 assertions, 0 failures, 0 errors, 0 skips
```

Is ```Array[Integer]``` going to be fixed in future versions of Grape ?

Thanks

-
Nicolas Gonzalez

### PR DESCRIPTION
**Pull request by ngonzalez**
Fixes #1324, Allow using ```coerce_with``` when type is either ```Array[String]``` or ```Array[Integer]```

### CODE REVIEW

File: lib/grape/validations/types/custom_type_coercer.rb [hunk 1]
```diff
@@ -136,9 +136,13 @@ def infer_type_check(type)
             # Note that this will fail unless a method is also
             # passed, or if the type also implements a parse() method.
             type
+          elsif type == [Integer]
```
Comment (dblock) [inline lib/grape/validations/types/custom_type_coercer.rb]: This seems like a 1-off, shouldn't it be that `type.is_a?(Enumerable)` of 1 simple type, and then it's `value.all?` of that type?

**Comment by dblock** [comment]
Will need CHANGELOG and possibly README changes.

**Comment by ngonzalez** [comment]
@dblock Requested changes have been done and the Pull Request is updated

File: CHANGELOG.md [hunk 2]
```diff
@@ -9,6 +9,8 @@
 
 #### Fixes
 
+* [#1325](https://github.com/ruby-grape/grape/pull/1325): Params: Fix coerce_with helper with Array types - [@ngonzalez](https://github.com/ngonzalez)
```
Comment (dblock) [inline CHANGELOG.md]: This is missing a period at the end ;)

File: README.md [hunk 3]
```diff
@@ -797,6 +797,15 @@ params do
 end
 ```
 
+Alternative (simpler) example using coerce_with in params:
```
Comment (dblock) [inline README.md]: Backtick quote `coerce_with` as code.

File: README.md [hunk 4]
```diff
@@ -797,6 +797,15 @@ params do
...
+This will take a string in input and output an Array of Integers.
+Like the Color parser example, coerce_with could have used a class with a parse method.
+```ruby
```
Comment (dblock) [inline README.md]: Add an empty line above. Backtick-quote the method names, `coerce_with` and `parse`. Basically make it look like the rest of the README (and if you find any other inconsistencies please feel free to fix).

**Comment by dblock** [comment]
Looks good. I only have minor text requests and I'll merge. Thanks for the good work.

**Comment by ngonzalez** [comment]
@dblock Thanks for the code review  ^ ^ I updated README and CHANGELOG

**Comment by dblock** [comment]
Merged, thanks!
